name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "wheres-waldo-app"
          heroku_email: "robjmorandini@hotmail.com"
          healthcheck: "https://wheres-waldo-app.herokuapp.com/health"
          checkstring: "ok"
        env:
          HD_DEV_DB_URL: ${{secrets.DEV_DB_URL}}